package com.example.msp.greendao.entity.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CETENTITY".
 */
public class CETEntity {

    private String word;
    private String english;
    private String china;
    private String sign;

    public CETEntity() {
    }

    public CETEntity(String word, String english, String china, String sign) {
        this.word = word;
        this.english = english;
        this.china = china;
        this.sign = sign;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getEnglish() {
        return english;
    }

    public void setEnglish(String english) {
        this.english = english;
    }

    public String getChina() {
        return china;
    }

    public void setChina(String china) {
        this.china = china;
    }

    public String getSign() {
        return sign;
    }

    public void setSign(String sign) {
        this.sign = sign;
    }

}
