package com.example.msp.greendao.entity.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.msp.greendao.entity.greendao.WisdomEntity;
import com.example.msp.greendao.entity.greendao.CETEntity;

import com.example.msp.greendao.entity.greendao.WisdomEntityDao;
import com.example.msp.greendao.entity.greendao.CETEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wisdomEntityDaoConfig;
    private final DaoConfig cETEntityDaoConfig;

    private final WisdomEntityDao wisdomEntityDao;
    private final CETEntityDao cETEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wisdomEntityDaoConfig = daoConfigMap.get(WisdomEntityDao.class).clone();
        wisdomEntityDaoConfig.initIdentityScope(type);

        cETEntityDaoConfig = daoConfigMap.get(CETEntityDao.class).clone();
        cETEntityDaoConfig.initIdentityScope(type);

        wisdomEntityDao = new WisdomEntityDao(wisdomEntityDaoConfig, this);
        cETEntityDao = new CETEntityDao(cETEntityDaoConfig, this);

        registerDao(WisdomEntity.class, wisdomEntityDao);
        registerDao(CETEntity.class, cETEntityDao);
    }
    
    public void clear() {
        wisdomEntityDaoConfig.getIdentityScope().clear();
        cETEntityDaoConfig.getIdentityScope().clear();
    }

    public WisdomEntityDao getWisdomEntityDao() {
        return wisdomEntityDao;
    }

    public CETEntityDao getCETEntityDao() {
        return cETEntityDao;
    }

}
